import assert from "node:assert/strict";
import express from "express";
import session from "express-session";
import sharp from "sharp";

// Never use production storage, email, OAuth or AI during these integration checks.
Object.assign(process.env, { USE_LOCAL_DB: "true", LOCAL_DATABASE_PATH: ".local/security-integration", NODE_ENV: "test", STRIPE_SECRET_KEY: "sk_test_local_only", GOOGLE_CLIENT_ID: "", GOOGLE_CLIENT_SECRET: "", RESEND_API: "", RESEND_API_KEY: "", GEMINI_API_KEY: "local-test", GOOGLE_API_KEY: "local-test", OPENAI_API_KEY: "local-test", REPLICATE_API_TOKEN: "local-test", JWT_SECRET: "local-security-test-secret-not-for-production", APP_URL: "" });
const { db, ensureSecuritySchema } = await import("../server/db");
const { sql } = await import("drizzle-orm");
const { storage } = await import("../server/storage");
const { registerRoutes } = await import("../server/routes");
const { registerAuthRoutes } = await import("../server/auth-routes");
const { registerOnboardingRoutes } = await import("../server/onboarding-routes");
const { setupGoogleAuth } = await import("../server/google-auth");
const { jobToken, validJobToken, requestSecurity, securityErrorHandler, acquireLease, releaseLease } = await import("../server/security");
const { AuthService } = await import("../server/auth");
const { isPublicAddress, publicHttpsUrl } = await import("../server/safe-request");
const { validateRegionMask, compositeRegion } = await import("../server/region-edit");
await ensureSecuritySchema();
await db.execute(sql`INSERT INTO subscription_plans (id, name, price, interval, visualization_limit, embed_access, active) VALUES ('free', 'Free', 0, 'month', 5, false, true) ON CONFLICT DO NOTHING`);
await db.execute(sql`DELETE FROM security_rate_limits`);
const app = express();
app.use(requestSecurity);
app.use(express.json());
app.use(session({ secret: "isolated-test-session-secret", resave: false, saveUninitialized: false, cookie: { httpOnly: true } }));
setupGoogleAuth(app);
registerAuthRoutes(app);
registerOnboardingRoutes(app);
const server = await registerRoutes(app);
app.use(securityErrorHandler);
await new Promise<void>(resolve => server.listen(0, "127.0.0.1", resolve));
const base = `http://127.0.0.1:${(server.address() as any).port}`;
async function request(path: string, method = "GET", body?: any, cookie = "", headers: Record<string,string> = {}) {
  return fetch(base + path, { method, headers: { ...(body ? { "content-type": "application/json" } : {}), cookie, ...headers }, body: body ? JSON.stringify(body) : undefined });
}
const suffix = Date.now();
const credentials = (label: string) => ({ email: `${label}-${suffix}@example.test`, password: "local-password-123", firstName: "Test", lastName: label, termsAccepted: true });
try {
  assert.equal((await request("/api/auth/register", "POST", { ...credentials("invalid"), termsAccepted: false })).status, 400);
  const a = await request("/api/auth/register", "POST", credentials("a"));
  assert.equal(a.status, 201, await a.clone().text());
  const cookieA = a.headers.getSetCookie().map(c => c.split(";")[0]).join("; ");
  assert.match(a.headers.getSetCookie().join(""), /HttpOnly/);
  const userA = (await a.json()).data.user;
  assert.equal(userA.emailVerified, false);
  const b = await request("/api/auth/register", "POST", credentials("b"));
  assert.equal(b.status, 201);
  const cookieB = b.headers.getSetCookie().map(c => c.split(";")[0]).join("; ");
  const userB = (await b.json()).data.user;
  assert.equal((await request("/api/auth/me", "GET", undefined, cookieA)).status, 200);
  assert.equal((await request("/api/auth/me")).status, 401);
  const setup = await request("/api/workspace/setup", "GET", undefined, cookieA);
  assert.equal(setup.status, 200, await setup.clone().text());
  const tenant = (await setup.json()).tenant;
  const settings = { companyName: "Test Exteriors", logoUrl: "", primaryColor: "#123456", phone: "", trade: "roofing", exteriorOptions: { roof: [], siding: [{ label: "Lap siding", prompt: "Smooth horizontal lap" }], windows: [] }, roofColors: [], sidingColors: [{ label: "Blue", hex: "#6b858e" }], windowColors: [] };
  assert.equal((await request("/api/workspace/setup", "PUT", settings, cookieA)).status, 200);
  assert.equal((await request("/api/workspace/setup", "PUT", { ...settings, userId: userB.id }, cookieA)).status, 400);
  assert.equal((await request("/api/workspace/setup", "PUT", settings, cookieA, {origin:"https://untrusted.example"})).status, 403);
  const reloaded = await (await request("/api/workspace/setup", "GET", undefined, cookieA)).json();
  assert.equal(reloaded.tenant.companyName, "Test Exteriors");
  assert.equal(reloaded.tenant.embedCustomizations.exteriorOptions.siding[0].label, "Lap siding");
  assert.equal((await request("/api/workspace/publish", "POST", {}, cookieA)).status, 403);
  const invalidUpload = new FormData(); invalidUpload.append("image", new Blob(["not an image"]), "bad.jpg");
  assert.equal((await fetch(base + "/api/upload-image", {method:"POST",headers:{cookie:cookieA},body:invalidUpload})).status,400);
  const largeUpload = new FormData(); largeUpload.append("image",new Blob([Buffer.alloc(16*1024*1024)]),"large.jpg");
  assert.equal((await fetch(base + "/api/upload-image", {method:"POST",headers:{cookie:cookieA},body:largeUpload})).status,413);
  await db.execute(sql`INSERT INTO subscription_plans (id,name,price,interval,visualization_limit,embed_access,active) VALUES ('price_1TcynuBY2SPm2HvO1Eri2ogI','Contractor',30000,'month',200,true,true) ON CONFLICT DO NOTHING`);
  const active = await storage.getUserActiveSubscription(userA.id);
  await storage.updateSubscription(active!.id,{planId:"price_1TcynuBY2SPm2HvO1Eri2ogI"});
  await storage.updateUser(userA.id,{emailVerified:true} as any);
  const launch = await request("/api/workspace/publish","POST",{},cookieA);
  assert.equal(launch.status,200,await launch.clone().text());
  assert.match((await launch.json()).path,/^\/embed-roofing\?tenant=account-/);
  assert.ok((await (await request("/api/workspace/setup","GET",undefined,cookieA)).json()).onboarding.publishedAt);
  const generation = await storage.createVisualization({ tenantId: tenant.id, userId: userA.id, originalImageUrl: "private-original", generatedImageUrl: "private-result", status: "completed" });
  const statusPath = `/api/visualizations/${generation.id}/status`;
  assert.equal((await request(statusPath)).status, 401);
  assert.equal((await request(statusPath, "GET", undefined, cookieB)).status, 404);
  assert.equal((await request(statusPath, "GET", undefined, cookieA)).status, 200);
  const capability = jobToken("visualizations", generation.id);
  assert.equal((await request(statusPath, "GET", undefined, "", {"x-generation-token":capability})).status, 200);
  assert.equal(validJobToken(capability,"pools",generation.id),false);
  assert.equal(validJobToken(capability,"visualizations",generation.id+1),false);
  assert.equal(validJobToken(capability+"x","visualizations",generation.id),false);
  assert.equal((await request(`/api/tenants/${tenant.id}/visualizations`, "GET", undefined, cookieB)).status, 404);
  assert.equal((await request(`/api/tenants/${tenant.id}/visualizations`)).status, 401);
  assert.equal((await request(`/api/debug/user/${userA.id}/embed`)).status, 404);
  assert.equal((await request("/api/analyze", "POST", {})).status, 401);
  const teamA = await storage.createTeam({ ownerId:userA.id,name:"A" });
  const teamB = await storage.createTeam({ ownerId:userB.id,name:"B" });
  const memberB = await storage.addTeamMember({teamId:teamB.id,email:`member-${suffix}@example.test`,role:"member",status:"active"});
  assert.equal((await request(`/api/teams/${teamA.id}/members/${memberB.id}`,"PATCH",{status:"deactivated"},cookieA)).status,404);
  assert.equal((await request(`/api/teams/${teamA.id}/members/${memberB.id}`,"DELETE",undefined,cookieA)).status,404);
  assert.equal((await storage.getTeamMembers(teamB.id)).length,1);
  const leaseKey = `test:${suffix}`;
  const claims = await Promise.all([acquireLease(leaseKey),acquireLease(leaseKey)]);
  assert.equal(claims.filter(Boolean).length,1);
  await releaseLease(leaseKey,claims.find(Boolean)!);
  for(const address of ["127.0.0.1","10.1.1.1","169.254.169.254","100.64.0.1","::1","::ffff:127.0.0.1","2002:7f00:1::"]) assert.equal(isPublicAddress(address),false,address);
  assert.equal(isPublicAddress("8.8.8.8"),true);
  assert.throws(() => publicHttpsUrl("https://user:password@example.com"));
  assert.throws(() => publicHttpsUrl("http://example.com"));
  const original = await sharp({create:{width:10,height:10,channels:3,background:"red"}}).png().toBuffer();
  const generated = await sharp({create:{width:10,height:10,channels:3,background:"blue"}}).png().toBuffer();
  const maskBytes = Buffer.alloc(100); maskBytes[55]=255;
  const maskPng = await sharp(maskBytes,{raw:{width:10,height:10,channels:1}}).png().toBuffer();
  const mask = await validateRegionMask(`data:image/png;base64,${maskPng.toString("base64")}`,original);
  const edited = await sharp(await compositeRegion(original,generated,mask)).removeAlpha().raw().toBuffer();
  for(let pixel=0;pixel<100;pixel++) assert.deepEqual([...edited.subarray(pixel*3,pixel*3+3)],pixel === 55 ? [0,0,255] : [255,0,0]);
  const bearer = AuthService.generateToken((await storage.getUser(userA.id))!);
  assert.equal((await request("/api/auth/logout","POST",{},cookieA)).status,200);
  assert.equal((await request("/api/auth/me","GET",undefined,cookieA)).status,401);
  assert.equal((await request("/api/auth/me","GET",undefined,"",{authorization:`Bearer ${bearer}`})).status,403);
  console.log("PASS: signup, sessions/logout, cross-tenant reads and membership, setup persistence, publish gates, CSRF, job capabilities, concurrency leases, SSRF address validation, exact outside-mask preservation.");
} finally { server.close(); }
process.exit(0);
